name: "Gradle Wrapper"
on: [push, pull_request]
permissions: read-all
jobs:
  validation:
    name: "validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b # tag=v1
